module.exports = {
  SPRINKL_ENVIRONMENT: 'SPRINKL_ENVIRONMENT',
  SPRINKL_APP_ID: 'SPRINKL_APP_ID',
  SPRINKL_LANDING_PAGE_URL: 'SPRINKL_LANDING_PAGE_URL',
  SPRINKL_TIMEZONE: 'SPRINKL_TIMEZONE',
  SPRINKL_RESPONSE_POLL_INTERVAL: 'SPRINKL_RESPONSE_POLL_INTERVAL',
  SPRINKL_USER_AGENT: 'SPRINKL_USER_AGENT',
  SPRINKL_FALLBACK_LOCALES: 'SPRINKL_FALLBACK_LOCALES',
  SPRINKL_CHAT_USER: 'SPRINKL_CHAT_USER',
  SPRINKL_CUSTOM_CONTEXT: 'SPRINKL_CUSTOM_CONTEXT',
  SPRINKL_STARTED_BY_CONTEXT: 'SPRINKL_STARTED_BY_CONTEXT'
}
